### PR TITLE
docker: use host network for simplicity

### PR DESCRIPTION
**Pull request by dangbert**
Have docker use host network so that referencing `address='127.0.0.1'` works in send_commands.py

This way students using docker won't have to update the IP address on this line.

### CODE REVIEW

**Comment by portaloffreedom** [comment]
This is very cool! thanks!

**Comment by JJWRoeloffs** [comment]
Reverted this change in the rewrite.

`--net=host` does not do what you think it does: it sets the net equal to the kernel it is virtualizing, not to the host system. When Docker is installed via docker desktop, this virtualized kernel is the Linux kernel that is running in the Docker Desktop virtual machine / WSL system, meaning setting `--net=host` effectively does nothing there.

**Comment by dangbert** [comment]
I was only able to test this myself on linux at the time, and made some assumptions about the other OS's as indeed I read now there seems to be an extra layer of virtualization on docker desktop for windows/mac that complicates things.  

For what it's worth I don't believe this PR had a negative effect though as the students got through the course last January without raising this as an issue.

**Comment by JJWRoeloffs** [comment]
Oh, yeah, totally. I didn't realise until I tested on Windows myself, either.

I just made a quick comment here to notify anyone going through the pull requests and stuff like that _why_ I didn't include it, and also because I closed your other one. :P

**Pull request merged**
